### ISSUE TITLE
My requests in oc interface isn't properly showing my requests

### ISSUE THREAD

**Issue by pripley123** [bcgov/OCWA#55]
## User Story
**As an** output checker ,<br>
**I want**  to be able to see requests assigned [claimed] by me<br>
**so that** I can easily find requests I am associated with.

## Test Case

# ENV
`TEST`

# TESTCASE
1. Log in an output checker
2. Assign an unassigned request to yourself
3. On the main [Kanban view] page filter my "My Requests"

# EXPECTED
I would see the request I just assigned to myself

# ACTUAL
I don't see the request I just assigned to myself.  Interestingly, some older requests that have been previously claimed do show.

**Comment by Jonesy** [comment]
This should be fixed with #49, the requests were switched to be assigned by username instead of email so I made the fixes in the UI filters to reflect this (as assigned by the `user.idField` in the config.

**Comment by pripley123** [comment]
Tried in test environment - same behaviour as described in the issue description is still occurring.  Moving to in-progress
